name: Copy docs folder to flutterflow branch

on: [push]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: main
          branches: flutterflow
          files: README.md docs/*
