name: Copy docs folder to flutterflow branch

on: [push]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Copy using git commands
        run: |
          git config --global --add safe.directory
          git checkout flutterflow
          git checkout main -- README.md
          git checkout main -- docs/*
          git add README.md docs/*
          git commit -m "Adding the docs required from main"
          git push origin flutterflow
