name: Copy docs folder to flutterflow branch

on: [push]
jobs:
  copy:
    name: Copy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'docs'
          TARGET_BRANCH: 'docs'
        run: |
          files=""
          
          # Use find to get the list of files and read them one by one
          while IFS= read -r -d '' file; do
              # Append each file to the files string, properly quoted
              files="$files '$file'"
          done < <(find "$SRC_FOLDER_PATH" -type f -print0)
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          eval "git checkout ${GITHUB_REF##*/} -- $files" # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
